{% set version = '0.1.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sourcetools
  version: {{ version|replace("-", "_") }}

source:
  fn: sourcetools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sourcetools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sourcetools/sourcetools_{{ version }}.tar.gz


  sha256: 47984406efb3b3face133979ccbae9fefb7360b9a6ca1a1c11473681418ed2ca

build:
  merge_build_host: True  # [win]
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win32]

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('sourcetools')"  # [not win]
    - "\"%R%\" -e \"library('sourcetools')\""  # [win]



about:
  home: https://CRAN.R-project.org/package=sourcetools
  license: MIT
  summary: Tools for the reading and tokenization of R code. The 'sourcetools' package provides
    both an R and C++ interface for the tokenization of R code, and helpers for interacting
    with the tokenized representation of R code.
  license_family: MIT
  license_file: LICENSE



extra:
  recipe-maintainers:
    - croth1
