# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxr_base3.4.1
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxr_base3.5.1
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxr_base3.4.1
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxr_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HWlWnC9HDgFc+gPJvCwlpmpqKWB/gQko56TUFSwxjmAUB+12vxQ6vt0sJG4Id8UiQXmBS2OHWzATVQkvBoBSrMWUEokFWCChEgHE6G7PkClOoLsRlKjRThsgCKYhC5zu0BFBEgKHNJWN/uQQbFqvWYQrpjQ9EzY5g6XoPmdrEIEIZTe3TMw1UgxKpodjaN0qsx2jGO4pWp+I2X/NtJxvjhqJd+RoGeHNqom9RcUbro/lNy7doh96KXcyByPPdUA+QET0j0CQBL8rJHmybm17wq+NVvfyN7PIx/u9J3GNWjycX8vpRvR4Pv/QKz8NgbBHqSMCGrvZKWUQenzWt01U+Yo8KzukBU88Ao0AUXvi+wou6hKGkDjPJ3T2hIuCDUbA5U0/zYPgxvwQ+w+6tsCS9+MN/TG5Hhp8o3yircnfXF474ZGdPL/6tnEJiuRFGuC3TKw/0RSEGImrkFo2HUMyk7rOHmmrybONJY7ubdTifD03EtVHY8mhR8EHHUPwk6pC5a23InN5My9cY7JdRhXeHVut2k+10U7bb2YYeZ36pWf/0dZrBKl1UhNBGpS5aBWkgsq7vwdq3ib6pB2ro+e+2eLVQN/9jc/dsurKxwDcQ8+rNedptmqryQ4WVl5OOWT6DEcTy6C7YNsrC6en8zVwyNWoMZzT2zBmMbVyL0dSydQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
