# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HWlWnC9HDgFc+gPJvCwlpmpqKWB/gQko56TUFSwxjmAUB+12vxQ6vt0sJG4Id8UiQXmBS2OHWzATVQkvBoBSrMWUEokFWCChEgHE6G7PkClOoLsRlKjRThsgCKYhC5zu0BFBEgKHNJWN/uQQbFqvWYQrpjQ9EzY5g6XoPmdrEIEIZTe3TMw1UgxKpodjaN0qsx2jGO4pWp+I2X/NtJxvjhqJd+RoGeHNqom9RcUbro/lNy7doh96KXcyByPPdUA+QET0j0CQBL8rJHmybm17wq+NVvfyN7PIx/u9J3GNWjycX8vpRvR4Pv/QKz8NgbBHqSMCGrvZKWUQenzWt01U+Yo8KzukBU88Ao0AUXvi+wou6hKGkDjPJ3T2hIuCDUbA5U0/zYPgxvwQ+w+6tsCS9+MN/TG5Hhp8o3yircnfXF474ZGdPL/6tnEJiuRFGuC3TKw/0RSEGImrkFo2HUMyk7rOHmmrybONJY7ubdTifD03EtVHY8mhR8EHHUPwk6pC5a23InN5My9cY7JdRhXeHVut2k+10U7bb2YYeZ36pWf/0dZrBKl1UhNBGpS5aBWkgsq7vwdq3ib6pB2ro+e+2eLVQN/9jc/dsurKxwDcQ8+rNedptmqryQ4WVl5OOWT6DEcTy6C7YNsrC6en8zVwyNWoMZzT2zBmMbVyL0dSydQ="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi