travis:
  secure:
    BINSTAR_TOKEN: fK7dpXFILMsPaS0mdhofpy3Ch1QK3sOR25zKWk2KBQaxKB/X5FW8zbXPn1m99P6DsuTR+wQsv4qS3GA7SJcRHX75AegYszXKiltpQFHIL9tbhPQtaVkt1zHup33TFUUKpAFEk/wcKpbyHqIe+kHirq0PUjyK4Bx1i9JPee2W9hCAESeFwJuyG+F3S3mnkn8WgZssUSLkhh6HTSAFl6zlFcDPcEixlkl1dhQI85q0O7LB2bT+Vh3IOPiNbhjKg9w+dLN9d9+Mqtj2K+vyxYqbIsdjhtX6UgjrrwddFSN8/RWEefelb56JClrHfHL66jZBW+9kL389hJVeT6YhqXECy8DcbEPeDwkUKQC57BNp1AsWJloC2d/l/7N73PnBVgOQAmjbV3EVngxTKHlJwIilH+MSSmgjuj1Xllpu/ZcEERrFcAtwT6DRrfOKMG8rV3BViqIWsELaz9QSq6IARNa9dSCxmK51Hr1Y8mdCANLaBKszdpSvhjJazm4/NiPkJ2/yKSTFLXQzTuqWPdH8lgRXhiJW5vRgC8ki3f0Mxr/7yELw7BqlwMqf1+n6D5QIbNvdlNt0LY7U8r/18odn7NZAJl9WspOT95Yh7/h6br/pBD9vu3qU2BuI7ULh2OOZ4V+Dw8e/Z1JxhsQTlqJO7hP4vNMNt1CqDNpoRM6cmtIPnPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
