appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: HWlWnC9HDgFc+gPJvCwlpmpqKWB/gQko56TUFSwxjmAUB+12vxQ6vt0sJG4Id8UiQXmBS2OHWzATVQkvBoBSrMWUEokFWCChEgHE6G7PkClOoLsRlKjRThsgCKYhC5zu0BFBEgKHNJWN/uQQbFqvWYQrpjQ9EzY5g6XoPmdrEIEIZTe3TMw1UgxKpodjaN0qsx2jGO4pWp+I2X/NtJxvjhqJd+RoGeHNqom9RcUbro/lNy7doh96KXcyByPPdUA+QET0j0CQBL8rJHmybm17wq+NVvfyN7PIx/u9J3GNWjycX8vpRvR4Pv/QKz8NgbBHqSMCGrvZKWUQenzWt01U+Yo8KzukBU88Ao0AUXvi+wou6hKGkDjPJ3T2hIuCDUbA5U0/zYPgxvwQ+w+6tsCS9+MN/TG5Hhp8o3yircnfXF474ZGdPL/6tnEJiuRFGuC3TKw/0RSEGImrkFo2HUMyk7rOHmmrybONJY7ubdTifD03EtVHY8mhR8EHHUPwk6pC5a23InN5My9cY7JdRhXeHVut2k+10U7bb2YYeZ36pWf/0dZrBKl1UhNBGpS5aBWkgsq7vwdq3ib6pB2ro+e+2eLVQN/9jc/dsurKxwDcQ8+rNedptmqryQ4WVl5OOWT6DEcTy6C7YNsrC6en8zVwyNWoMZzT2zBmMbVyL0dSydQ=}
bot:
  automerge: true
